version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db4free.net:3306/sql7788016
      SPRING_DATASOURCE_USERNAME: sql7788016
      SPRING_DATASOURCE_PASSWORD: 1Ew5EGdjA8

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1Ew5EGdjA8
      MYSQL_DATABASE: sql7788016
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
